import { LocaleSwitcher } from "./components/LocaleSwitcher";
import Navbar from "./components/Navbar";



export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'bn' }]
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children , params}) {
  return (
    <html lang={params.lang}>
      <body >
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
