import "../globals.css";
import Navbar from "./components/Navbar";



export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'bn' }]
}

export const metadata = {
  title: "Multilanguage next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children , params:{lang}}) {
  return (
    <html lang={lang}>
      <body >
        <Navbar lang={lang}></Navbar>
        {children}
        </body>
    </html>
  );
}
